version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - '3000:80'
    depends_on:
      - server

  server:
    build:
      context: ./server
    command: gunicorn --bind 0.0.0.0:8000 nexus.wsgi:application
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
