# Generated by Django 5.0.6 on 2024-07-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapi', '0012_alter_category_icon_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='nexusapi.product'),
        ),
    ]
