# Generated by Django 5.0.6 on 2024-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
