# Generated by Django 5.0.6 on 2024-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapi', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='static/category_icons/placeholder.svg', null=True, upload_to='category_icons/'),
        ),
    ]
